// Cocktail data for Cocktail Flow.
// The categories follow cocktailflow.com's taxonomy: base spirit, type, strength and colour,
// plus a few themed collections. Recipes are well-known classics, curated by hand.

const INGREDIENT_GROUPS = {
  "Spirits": [
    "Gin", "Vodka", "White rum", "Dark rum", "Tequila", "Mezcal", "Bourbon", "Rye whiskey",
    "Scotch whisky", "Irish whiskey", "Brandy", "Cachaça", "Pisco", "Absinthe"
  ],
  "Liqueurs": [
    "Triple sec", "Campari", "Aperol", "Coffee liqueur", "Amaretto", "Blue curaçao",
    "Peach schnapps", "Maraschino liqueur", "Elderflower liqueur", "Irish cream",
    "Crème de menthe", "Crème de cacao", "Crème de cassis", "Chambord", "Bénédictine",
    "Chartreuse", "Galliano", "Melon liqueur", "Coconut rum", "Drambuie"
  ],
  "Wine & Beer": [
    "Sweet vermouth", "Dry vermouth", "Champagne", "Prosecco", "Lager", "Stout", "Red wine"
  ],
  "Mixers": [
    "Soda water", "Tonic water", "Cola", "Ginger beer", "Ginger ale", "Lemonade", "Iced tea", "Espresso"
  ],
  "Juices": [
    "Lime juice", "Lemon juice", "Orange juice", "Pineapple juice", "Cranberry juice",
    "Grapefruit juice", "Tomato juice", "Peach purée", "Passion fruit purée", "Apple juice"
  ],
  "Sweeteners": [
    "Simple syrup", "Sugar", "Grenadine", "Honey", "Agave syrup", "Orgeat", "Coconut cream"
  ],
  "Dairy & eggs": ["Cream", "Milk", "Egg white", "Vanilla ice cream"],
  "Bitters & spice": [
    "Angostura bitters", "Orange bitters", "Peychaud's bitters", "Worcestershire sauce",
    "Tabasco", "Salt", "Celery salt", "Nutmeg", "Cinnamon"
  ],
  "Fresh": ["Mint", "Lime", "Lemon", "Orange", "Strawberries", "Cucumber", "Coffee (hot)", "Hot water"]
};

// Things most kitchens already have. Toggleable in the UI.
const PANTRY_BASICS = ["Sugar", "Salt", "Hot water"];

// The bottles that define each spirit family (used by the "New Direction" shopping suggestion).
const BASE_SPIRITS = {
  gin: ["Gin"],
  vodka: ["Vodka"],
  rum: ["White rum", "Dark rum", "Cachaça", "Coconut rum"],
  tequila: ["Tequila", "Mezcal"],
  whiskey: ["Bourbon", "Rye whiskey", "Scotch whisky", "Irish whiskey"],
  brandy: ["Brandy", "Pisco"],
  champagne: ["Champagne", "Prosecco", "Red wine"],
  beer: ["Lager", "Stout"]
};

// Category taxonomy, mirroring cocktailflow.com.
const CATEGORIES = {
  base: {
    label: "Base spirit",
    values: {
      gin: "Gin", vodka: "Vodka", rum: "Rum", tequila: "Tequila & Mezcal", whiskey: "Whiskey",
      brandy: "Brandy", champagne: "Champagne & Wine", beer: "Beer", liqueur: "Liqueur",
      "non-alcoholic": "Non-alcoholic"
    }
  },
  type: {
    label: "Type",
    values: {
      classic: "Classic", long: "Long drink", tropical: "Tropical", creamy: "Creamy",
      shooter: "Shooter", frozen: "Frozen", hot: "Hot drink", sour: "Sour", "non-alcoholic": "Non-alcoholic"
    }
  },
  strength: {
    label: "Strength",
    values: { light: "Light", medium: "Medium", strong: "Strong" }
  },
  color: {
    label: "Colour",
    values: {
      red: "Red", pink: "Pink", orange: "Orange", yellow: "Yellow", green: "Green",
      blue: "Blue", brown: "Brown", white: "White", clear: "Clear"
    }
  },
  collection: {
    label: "Collections",
    values: {
      "allseason-classics": "All Seasons Classics", "summer": "Summer Sippers",
      "party": "Party Crowd-Pleasers", "brunch": "Brunch", "after-dinner": "After Dinner",
      "engagement-party": "Engagement Party"
    }
  }
};

// ings: [ingredient, amount] — ingredient names must match INGREDIENT_GROUPS exactly.
const COCKTAILS = [
  // ---------- Gin ----------
  { name: "Gin & Tonic", base: "gin", type: "long", strength: "light", color: "clear", glass: "Highball",
    ings: [["Gin", "50 ml"], ["Tonic water", "150 ml"]], garnish: "Lime wedge",
    method: "Fill a highball with ice, add gin, top with tonic and stir gently.", collections: ["allseason-classics", "summer", "party"] },
  { name: "Negroni", base: "gin", type: "classic", strength: "strong", color: "red", glass: "Rocks",
    ings: [["Gin", "30 ml"], ["Campari", "30 ml"], ["Sweet vermouth", "30 ml"]], garnish: "Orange peel",
    method: "Stir all ingredients with ice and strain over a large ice cube.", collections: ["allseason-classics"] },
  { name: "Dry Martini", base: "gin", type: "classic", strength: "strong", color: "clear", glass: "Martini",
    ings: [["Gin", "60 ml"], ["Dry vermouth", "10 ml"]], garnish: "Olive or lemon twist",
    method: "Stir with ice until very cold and strain into a chilled martini glass.", collections: ["allseason-classics", "engagement-party"] },
  { name: "Tom Collins", base: "gin", type: "long", strength: "light", color: "clear", glass: "Collins",
    ings: [["Gin", "45 ml"], ["Lemon juice", "30 ml"], ["Simple syrup", "15 ml"], ["Soda water", "60 ml"]], garnish: "Lemon slice",
    method: "Shake gin, lemon and syrup with ice, strain into an ice-filled glass and top with soda.", collections: ["summer"] },
  { name: "Gimlet", base: "gin", type: "sour", strength: "strong", color: "green", glass: "Coupe",
    ings: [["Gin", "60 ml"], ["Lime juice", "20 ml"], ["Simple syrup", "15 ml"]], garnish: "Lime wheel",
    method: "Shake with ice and double strain into a chilled coupe.", collections: [] },
  { name: "Gin Fizz", base: "gin", type: "sour", strength: "light", color: "white", glass: "Highball",
    ings: [["Gin", "45 ml"], ["Lemon juice", "30 ml"], ["Simple syrup", "15 ml"], ["Egg white", "1"], ["Soda water", "30 ml"]], garnish: "Lemon peel",
    method: "Dry shake, then shake with ice. Strain into a chilled glass and top with soda.", collections: ["brunch"] },
  { name: "French 75", base: "gin", type: "classic", strength: "medium", color: "yellow", glass: "Flute",
    ings: [["Gin", "30 ml"], ["Lemon juice", "15 ml"], ["Simple syrup", "10 ml"], ["Champagne", "60 ml"]], garnish: "Lemon twist",
    method: "Shake gin, lemon and syrup with ice, strain into a flute and top with champagne.", collections: ["engagement-party", "party"] },
  { name: "Bee's Knees", base: "gin", type: "sour", strength: "medium", color: "yellow", glass: "Coupe",
    ings: [["Gin", "60 ml"], ["Lemon juice", "20 ml"], ["Honey", "20 ml"]], garnish: "Lemon twist",
    method: "Shake hard with ice and strain into a chilled coupe.", collections: [] },
  { name: "Aviation", base: "gin", type: "classic", strength: "strong", color: "blue", glass: "Coupe",
    ings: [["Gin", "45 ml"], ["Maraschino liqueur", "15 ml"], ["Lemon juice", "15 ml"], ["Crème de cassis", "5 ml"]], garnish: "Cherry",
    method: "Shake with ice and strain into a chilled coupe.", collections: [] },
  { name: "Bramble", base: "gin", type: "sour", strength: "medium", color: "red", glass: "Rocks",
    ings: [["Gin", "40 ml"], ["Lemon juice", "20 ml"], ["Simple syrup", "10 ml"], ["Chambord", "15 ml"]], garnish: "Blackberry",
    method: "Shake gin, lemon and syrup, pour over crushed ice and drizzle the Chambord on top.", collections: ["summer"] },
  { name: "Clover Club", base: "gin", type: "sour", strength: "medium", color: "pink", glass: "Coupe",
    ings: [["Gin", "45 ml"], ["Lemon juice", "15 ml"], ["Chambord", "15 ml"], ["Egg white", "1"]], garnish: "Raspberries",
    method: "Dry shake, then shake with ice and strain into a chilled coupe.", collections: ["engagement-party"] },
  { name: "Southside", base: "gin", type: "sour", strength: "medium", color: "green", glass: "Coupe",
    ings: [["Gin", "60 ml"], ["Lime juice", "25 ml"], ["Simple syrup", "20 ml"], ["Mint", "6 leaves"]], garnish: "Mint leaf",
    method: "Shake everything with ice and double strain.", collections: ["summer"] },
  { name: "Singapore Sling", base: "gin", type: "tropical", strength: "medium", color: "red", glass: "Hurricane",
    ings: [["Gin", "30 ml"], ["Bénédictine", "7 ml"], ["Triple sec", "7 ml"], ["Pineapple juice", "120 ml"], ["Lime juice", "15 ml"], ["Grenadine", "10 ml"], ["Angostura bitters", "1 dash"]], garnish: "Pineapple and cherry",
    method: "Shake with ice and strain into an ice-filled hurricane glass.", collections: ["summer"] },
  { name: "Corpse Reviver #2", base: "gin", type: "classic", strength: "strong", color: "yellow", glass: "Coupe",
    ings: [["Gin", "25 ml"], ["Triple sec", "25 ml"], ["Dry vermouth", "25 ml"], ["Lemon juice", "25 ml"], ["Absinthe", "1 dash"]], garnish: "Orange peel",
    method: "Shake with ice and strain into an absinthe-rinsed coupe.", collections: ["brunch"] },
  { name: "Last Word", base: "gin", type: "classic", strength: "strong", color: "green", glass: "Coupe",
    ings: [["Gin", "22 ml"], ["Chartreuse", "22 ml"], ["Maraschino liqueur", "22 ml"], ["Lime juice", "22 ml"]], garnish: "Cherry",
    method: "Shake with ice and strain into a chilled coupe.", collections: [] },

  // ---------- Vodka ----------
  { name: "Moscow Mule", base: "vodka", type: "long", strength: "light", color: "clear", glass: "Copper mug",
    ings: [["Vodka", "45 ml"], ["Ginger beer", "120 ml"], ["Lime juice", "10 ml"]], garnish: "Lime wedge",
    method: "Build over ice in a copper mug and stir.", collections: ["allseason-classics", "party"] },
  { name: "Cosmopolitan", base: "vodka", type: "classic", strength: "medium", color: "pink", glass: "Martini",
    ings: [["Vodka", "40 ml"], ["Triple sec", "15 ml"], ["Lime juice", "15 ml"], ["Cranberry juice", "30 ml"]], garnish: "Orange twist",
    method: "Shake with ice and strain into a chilled martini glass.", collections: ["party", "engagement-party"] },
  { name: "Espresso Martini", base: "vodka", type: "classic", strength: "medium", color: "brown", glass: "Martini",
    ings: [["Vodka", "50 ml"], ["Coffee liqueur", "20 ml"], ["Espresso", "30 ml"], ["Simple syrup", "10 ml"]], garnish: "3 coffee beans",
    method: "Shake hard with ice and double strain for a thick crema.", collections: ["after-dinner", "party"] },
  { name: "Bloody Mary", base: "vodka", type: "long", strength: "light", color: "red", glass: "Highball",
    ings: [["Vodka", "45 ml"], ["Tomato juice", "90 ml"], ["Lemon juice", "15 ml"], ["Worcestershire sauce", "3 dashes"], ["Tabasco", "2 dashes"], ["Celery salt", "1 pinch"]], garnish: "Celery stalk",
    method: "Roll between two tins with ice and strain into an ice-filled glass.", collections: ["brunch"] },
  { name: "Screwdriver", base: "vodka", type: "long", strength: "light", color: "orange", glass: "Highball",
    ings: [["Vodka", "50 ml"], ["Orange juice", "100 ml"]], garnish: "Orange slice",
    method: "Build over ice and stir.", collections: ["brunch"] },
  { name: "Cape Codder", base: "vodka", type: "long", strength: "light", color: "red", glass: "Highball",
    ings: [["Vodka", "45 ml"], ["Cranberry juice", "120 ml"]], garnish: "Lime wedge",
    method: "Build over ice and stir.", collections: [] },
  { name: "Sea Breeze", base: "vodka", type: "long", strength: "light", color: "pink", glass: "Highball",
    ings: [["Vodka", "40 ml"], ["Cranberry juice", "90 ml"], ["Grapefruit juice", "30 ml"]], garnish: "Lime wedge",
    method: "Build over ice and stir.", collections: ["summer"] },
  { name: "Sex on the Beach", base: "vodka", type: "long", strength: "light", color: "orange", glass: "Highball",
    ings: [["Vodka", "40 ml"], ["Peach schnapps", "20 ml"], ["Orange juice", "40 ml"], ["Cranberry juice", "40 ml"]], garnish: "Orange slice",
    method: "Build over ice and stir.", collections: ["summer", "party"] },
  { name: "White Russian", base: "vodka", type: "creamy", strength: "medium", color: "white", glass: "Rocks",
    ings: [["Vodka", "50 ml"], ["Coffee liqueur", "20 ml"], ["Cream", "30 ml"]], garnish: "",
    method: "Build vodka and coffee liqueur over ice and float the cream on top.", collections: ["after-dinner"] },
  { name: "Black Russian", base: "vodka", type: "classic", strength: "strong", color: "brown", glass: "Rocks",
    ings: [["Vodka", "50 ml"], ["Coffee liqueur", "20 ml"]], garnish: "",
    method: "Build over ice and stir.", collections: ["after-dinner"] },
  { name: "Lemon Drop", base: "vodka", type: "sour", strength: "medium", color: "yellow", glass: "Martini",
    ings: [["Vodka", "45 ml"], ["Triple sec", "15 ml"], ["Lemon juice", "25 ml"], ["Simple syrup", "10 ml"], ["Sugar", "rim"]], garnish: "Sugar rim",
    method: "Shake with ice and strain into a sugar-rimmed glass.", collections: ["party"] },
  { name: "Blue Lagoon", base: "vodka", type: "long", strength: "light", color: "blue", glass: "Highball",
    ings: [["Vodka", "40 ml"], ["Blue curaçao", "20 ml"], ["Lemonade", "120 ml"]], garnish: "Lemon slice",
    method: "Build over ice and stir.", collections: ["summer", "party"] },
  { name: "Kamikaze", base: "vodka", type: "shooter", strength: "strong", color: "clear", glass: "Shot",
    ings: [["Vodka", "20 ml"], ["Triple sec", "10 ml"], ["Lime juice", "10 ml"]], garnish: "",
    method: "Shake with ice and strain into shot glasses.", collections: ["party"] },
  { name: "Appletini", base: "vodka", type: "classic", strength: "medium", color: "green", glass: "Martini",
    ings: [["Vodka", "40 ml"], ["Apple juice", "30 ml"], ["Lemon juice", "10 ml"], ["Simple syrup", "10 ml"]], garnish: "Apple slice",
    method: "Shake with ice and strain into a chilled martini glass.", collections: [] },
  { name: "Porn Star Martini", base: "vodka", type: "tropical", strength: "medium", color: "yellow", glass: "Coupe",
    ings: [["Vodka", "40 ml"], ["Passion fruit purée", "30 ml"], ["Lime juice", "15 ml"], ["Simple syrup", "10 ml"], ["Prosecco", "50 ml (side)"]], garnish: "Half a passion fruit",
    method: "Shake with ice, strain into a coupe and serve with a shot of prosecco on the side.", collections: ["party", "engagement-party"] },
  { name: "Melon Ball", base: "vodka", type: "long", strength: "light", color: "green", glass: "Highball",
    ings: [["Vodka", "30 ml"], ["Melon liqueur", "30 ml"], ["Pineapple juice", "90 ml"]], garnish: "Melon ball",
    method: "Build over ice and stir.", collections: ["summer"] },

  // ---------- Rum ----------
  { name: "Mojito", base: "rum", type: "long", strength: "light", color: "green", glass: "Highball",
    ings: [["White rum", "50 ml"], ["Lime juice", "25 ml"], ["Simple syrup", "15 ml"], ["Mint", "8 leaves"], ["Soda water", "60 ml"]], garnish: "Mint sprig",
    method: "Gently muddle mint with lime and syrup, add rum and crushed ice, top with soda.", collections: ["allseason-classics", "summer", "party"] },
  { name: "Daiquiri", base: "rum", type: "sour", strength: "medium", color: "clear", glass: "Coupe",
    ings: [["White rum", "60 ml"], ["Lime juice", "25 ml"], ["Simple syrup", "15 ml"]], garnish: "Lime wheel",
    method: "Shake hard with ice and strain into a chilled coupe.", collections: ["allseason-classics"] },
  { name: "Strawberry Daiquiri", base: "rum", type: "frozen", strength: "light", color: "red", glass: "Hurricane",
    ings: [["White rum", "50 ml"], ["Lime juice", "20 ml"], ["Simple syrup", "15 ml"], ["Strawberries", "5"]], garnish: "Strawberry",
    method: "Blend everything with a cup of ice until smooth.", collections: ["summer"] },
  { name: "Piña Colada", base: "rum", type: "frozen", strength: "light", color: "white", glass: "Hurricane",
    ings: [["White rum", "50 ml"], ["Coconut cream", "30 ml"], ["Pineapple juice", "90 ml"]], garnish: "Pineapple wedge",
    method: "Blend with crushed ice until smooth.", collections: ["summer", "party"] },
  { name: "Cuba Libre", base: "rum", type: "long", strength: "light", color: "brown", glass: "Highball",
    ings: [["White rum", "50 ml"], ["Cola", "120 ml"], ["Lime juice", "10 ml"]], garnish: "Lime wedge",
    method: "Build over ice and stir.", collections: ["party"] },
  { name: "Dark 'n' Stormy", base: "rum", type: "long", strength: "light", color: "brown", glass: "Highball",
    ings: [["Dark rum", "60 ml"], ["Ginger beer", "100 ml"], ["Lime juice", "10 ml"]], garnish: "Lime wedge",
    method: "Fill with ice and ginger beer, then float the dark rum on top.", collections: [] },
  { name: "Mai Tai", base: "rum", type: "tropical", strength: "strong", color: "orange", glass: "Rocks",
    ings: [["White rum", "30 ml"], ["Dark rum", "30 ml"], ["Triple sec", "15 ml"], ["Orgeat", "15 ml"], ["Lime juice", "25 ml"]], garnish: "Mint sprig and lime shell",
    method: "Shake with crushed ice and pour unstrained.", collections: ["summer"] },
  { name: "Planter's Punch", base: "rum", type: "tropical", strength: "medium", color: "red", glass: "Highball",
    ings: [["Dark rum", "45 ml"], ["Orange juice", "35 ml"], ["Pineapple juice", "35 ml"], ["Lemon juice", "20 ml"], ["Grenadine", "10 ml"], ["Angostura bitters", "2 dashes"]], garnish: "Orange slice",
    method: "Shake with ice and strain into an ice-filled glass.", collections: ["summer", "party"] },
  { name: "Hurricane", base: "rum", type: "tropical", strength: "strong", color: "red", glass: "Hurricane",
    ings: [["White rum", "45 ml"], ["Dark rum", "45 ml"], ["Passion fruit purée", "30 ml"], ["Orange juice", "30 ml"], ["Lime juice", "15 ml"], ["Grenadine", "10 ml"]], garnish: "Orange slice and cherry",
    method: "Shake with ice and strain into an ice-filled hurricane glass.", collections: ["party"] },
  { name: "Painkiller", base: "rum", type: "tropical", strength: "medium", color: "yellow", glass: "Tiki mug",
    ings: [["Dark rum", "60 ml"], ["Pineapple juice", "120 ml"], ["Orange juice", "30 ml"], ["Coconut cream", "30 ml"], ["Nutmeg", "grated"]], garnish: "Grated nutmeg",
    method: "Shake with ice and pour into a tiki mug.", collections: ["summer"] },
  { name: "Blue Hawaiian", base: "rum", type: "tropical", strength: "light", color: "blue", glass: "Hurricane",
    ings: [["White rum", "30 ml"], ["Blue curaçao", "20 ml"], ["Pineapple juice", "60 ml"], ["Coconut cream", "30 ml"]], garnish: "Pineapple wedge",
    method: "Shake or blend with ice and pour into a hurricane glass.", collections: ["summer", "party"] },
  { name: "Hot Buttered Rum", base: "rum", type: "hot", strength: "medium", color: "brown", glass: "Mug",
    ings: [["Dark rum", "50 ml"], ["Sugar", "1 tsp"], ["Cinnamon", "1 pinch"], ["Hot water", "120 ml"]], garnish: "Cinnamon stick",
    method: "Stir rum, sugar and spice in a warm mug, top with hot water (and a pat of butter).", collections: ["after-dinner"] },
  { name: "Caipirinha", base: "rum", type: "classic", strength: "strong", color: "green", glass: "Rocks",
    ings: [["Cachaça", "60 ml"], ["Lime", "1/2"], ["Sugar", "2 tsp"]], garnish: "Lime wedge",
    method: "Muddle lime wedges with sugar, add cachaça and crushed ice and stir.", collections: ["summer"] },
  { name: "Malibu Sunset", base: "rum", type: "long", strength: "light", color: "orange", glass: "Highball",
    ings: [["Coconut rum", "45 ml"], ["Pineapple juice", "90 ml"], ["Grenadine", "10 ml"]], garnish: "Cherry",
    method: "Build rum and juice over ice, then slowly pour grenadine to sink.", collections: ["summer", "party"] },

  // ---------- Tequila & Mezcal ----------
  { name: "Margarita", base: "tequila", type: "sour", strength: "medium", color: "yellow", glass: "Margarita",
    ings: [["Tequila", "50 ml"], ["Triple sec", "20 ml"], ["Lime juice", "25 ml"], ["Salt", "rim"]], garnish: "Salt rim and lime",
    method: "Shake with ice and strain into a salt-rimmed glass.", collections: ["allseason-classics", "party", "summer"] },
  { name: "Frozen Margarita", base: "tequila", type: "frozen", strength: "medium", color: "green", glass: "Margarita",
    ings: [["Tequila", "50 ml"], ["Triple sec", "20 ml"], ["Lime juice", "25 ml"], ["Agave syrup", "10 ml"]], garnish: "Lime wheel",
    method: "Blend with a cup of ice until slushy.", collections: ["summer"] },
  { name: "Tommy's Margarita", base: "tequila", type: "sour", strength: "medium", color: "yellow", glass: "Rocks",
    ings: [["Tequila", "60 ml"], ["Lime juice", "30 ml"], ["Agave syrup", "15 ml"]], garnish: "Lime wheel",
    method: "Shake with ice and strain over fresh ice.", collections: [] },
  { name: "Paloma", base: "tequila", type: "long", strength: "light", color: "pink", glass: "Highball",
    ings: [["Tequila", "50 ml"], ["Grapefruit juice", "60 ml"], ["Lime juice", "10 ml"], ["Soda water", "60 ml"], ["Salt", "pinch"]], garnish: "Grapefruit wedge",
    method: "Build over ice with a pinch of salt, top with soda and stir.", collections: ["summer", "party"] },
  { name: "Tequila Sunrise", base: "tequila", type: "long", strength: "light", color: "orange", glass: "Highball",
    ings: [["Tequila", "45 ml"], ["Orange juice", "90 ml"], ["Grenadine", "15 ml"]], garnish: "Orange slice and cherry",
    method: "Build tequila and juice over ice, then sink the grenadine.", collections: ["summer", "brunch"] },
  { name: "El Diablo", base: "tequila", type: "long", strength: "light", color: "red", glass: "Highball",
    ings: [["Tequila", "45 ml"], ["Crème de cassis", "15 ml"], ["Lime juice", "15 ml"], ["Ginger beer", "90 ml"]], garnish: "Lime wedge",
    method: "Shake tequila, cassis and lime, strain over ice and top with ginger beer.", collections: [] },
  { name: "Mezcal Negroni", base: "tequila", type: "classic", strength: "strong", color: "red", glass: "Rocks",
    ings: [["Mezcal", "30 ml"], ["Campari", "30 ml"], ["Sweet vermouth", "30 ml"]], garnish: "Orange peel",
    method: "Stir with ice and strain over a large cube.", collections: [] },
  { name: "Tequila Slammer", base: "tequila", type: "shooter", strength: "medium", color: "clear", glass: "Shot",
    ings: [["Tequila", "25 ml"], ["Lemonade", "25 ml"]], garnish: "",
    method: "Pour into a sturdy shot glass, cover, slam on the table and drink while fizzing.", collections: ["party"] },

  // ---------- Whiskey ----------
  { name: "Old Fashioned", base: "whiskey", type: "classic", strength: "strong", color: "brown", glass: "Rocks",
    ings: [["Bourbon", "60 ml"], ["Simple syrup", "5 ml"], ["Angostura bitters", "2 dashes"]], garnish: "Orange peel",
    method: "Stir with ice and strain over a large ice cube.", collections: ["allseason-classics", "after-dinner"] },
  { name: "Manhattan", base: "whiskey", type: "classic", strength: "strong", color: "red", glass: "Coupe",
    ings: [["Rye whiskey", "60 ml"], ["Sweet vermouth", "30 ml"], ["Angostura bitters", "2 dashes"]], garnish: "Cherry",
    method: "Stir with ice and strain into a chilled coupe.", collections: ["allseason-classics"] },
  { name: "Whiskey Sour", base: "whiskey", type: "sour", strength: "medium", color: "yellow", glass: "Rocks",
    ings: [["Bourbon", "60 ml"], ["Lemon juice", "25 ml"], ["Simple syrup", "15 ml"], ["Egg white", "1"]], garnish: "Angostura drops and cherry",
    method: "Dry shake, then shake with ice and strain over fresh ice.", collections: ["allseason-classics"] },
  { name: "Mint Julep", base: "whiskey", type: "classic", strength: "strong", color: "green", glass: "Julep cup",
    ings: [["Bourbon", "60 ml"], ["Simple syrup", "10 ml"], ["Mint", "8 leaves"]], garnish: "Mint bouquet",
    method: "Lightly muddle mint with syrup, add bourbon and crushed ice, churn.", collections: ["summer"] },
  { name: "Boulevardier", base: "whiskey", type: "classic", strength: "strong", color: "red", glass: "Rocks",
    ings: [["Bourbon", "40 ml"], ["Campari", "25 ml"], ["Sweet vermouth", "25 ml"]], garnish: "Orange peel",
    method: "Stir with ice and strain over a large cube.", collections: ["after-dinner"] },
  { name: "Sazerac", base: "whiskey", type: "classic", strength: "strong", color: "brown", glass: "Rocks",
    ings: [["Rye whiskey", "60 ml"], ["Simple syrup", "5 ml"], ["Peychaud's bitters", "3 dashes"], ["Absinthe", "rinse"]], garnish: "Lemon peel",
    method: "Stir with ice and strain into an absinthe-rinsed chilled glass (no ice).", collections: [] },
  { name: "Penicillin", base: "whiskey", type: "sour", strength: "strong", color: "yellow", glass: "Rocks",
    ings: [["Scotch whisky", "60 ml"], ["Lemon juice", "20 ml"], ["Honey", "20 ml"]], garnish: "Candied ginger",
    method: "Shake with ice and strain over fresh ice.", collections: [] },
  { name: "Rusty Nail", base: "whiskey", type: "classic", strength: "strong", color: "brown", glass: "Rocks",
    ings: [["Scotch whisky", "45 ml"], ["Drambuie", "25 ml"]], garnish: "Lemon twist",
    method: "Stir over ice.", collections: ["after-dinner"] },
  { name: "Irish Coffee", base: "whiskey", type: "hot", strength: "medium", color: "brown", glass: "Irish coffee glass",
    ings: [["Irish whiskey", "40 ml"], ["Coffee (hot)", "120 ml"], ["Sugar", "2 tsp"], ["Cream", "30 ml"]], garnish: "Lightly whipped cream",
    method: "Stir whiskey and sugar into hot coffee, float lightly whipped cream on top.", collections: ["after-dinner"] },
  { name: "Hot Toddy", base: "whiskey", type: "hot", strength: "medium", color: "yellow", glass: "Mug",
    ings: [["Bourbon", "50 ml"], ["Honey", "15 ml"], ["Lemon juice", "15 ml"], ["Hot water", "120 ml"]], garnish: "Lemon wheel and cinnamon",
    method: "Stir everything together in a warm mug.", collections: ["after-dinner"] },
  { name: "Whiskey Highball", base: "whiskey", type: "long", strength: "light", color: "yellow", glass: "Highball",
    ings: [["Scotch whisky", "50 ml"], ["Soda water", "150 ml"]], garnish: "Lemon peel",
    method: "Build over plenty of ice and stir once.", collections: [] },
  { name: "Whiskey & Ginger", base: "whiskey", type: "long", strength: "light", color: "yellow", glass: "Highball",
    ings: [["Irish whiskey", "50 ml"], ["Ginger ale", "120 ml"]], garnish: "Lime wedge",
    method: "Build over ice and stir.", collections: ["party"] },
  { name: "Gold Rush", base: "whiskey", type: "sour", strength: "strong", color: "yellow", glass: "Rocks",
    ings: [["Bourbon", "60 ml"], ["Lemon juice", "25 ml"], ["Honey", "20 ml"]], garnish: "Lemon twist",
    method: "Shake with ice and strain over a large cube.", collections: [] },

  // ---------- Brandy ----------
  { name: "Sidecar", base: "brandy", type: "sour", strength: "strong", color: "orange", glass: "Coupe",
    ings: [["Brandy", "50 ml"], ["Triple sec", "20 ml"], ["Lemon juice", "20 ml"], ["Sugar", "rim"]], garnish: "Sugar rim",
    method: "Shake with ice and strain into a sugar-rimmed coupe.", collections: ["allseason-classics"] },
  { name: "Brandy Alexander", base: "brandy", type: "creamy", strength: "medium", color: "brown", glass: "Coupe",
    ings: [["Brandy", "30 ml"], ["Crème de cacao", "30 ml"], ["Cream", "30 ml"], ["Nutmeg", "grated"]], garnish: "Grated nutmeg",
    method: "Shake hard with ice and strain into a chilled coupe.", collections: ["after-dinner"] },
  { name: "Pisco Sour", base: "brandy", type: "sour", strength: "medium", color: "white", glass: "Coupe",
    ings: [["Pisco", "60 ml"], ["Lime juice", "30 ml"], ["Simple syrup", "20 ml"], ["Egg white", "1"], ["Angostura bitters", "3 drops"]], garnish: "Bitters drops",
    method: "Dry shake, shake with ice, strain and dot with bitters.", collections: [] },
  { name: "Stinger", base: "brandy", type: "classic", strength: "strong", color: "clear", glass: "Rocks",
    ings: [["Brandy", "50 ml"], ["Crème de menthe", "20 ml"]], garnish: "Mint sprig",
    method: "Stir with ice and strain over crushed ice.", collections: ["after-dinner"] },
  { name: "Vieux Carré", base: "brandy", type: "classic", strength: "strong", color: "brown", glass: "Rocks",
    ings: [["Brandy", "25 ml"], ["Rye whiskey", "25 ml"], ["Sweet vermouth", "25 ml"], ["Bénédictine", "5 ml"], ["Angostura bitters", "1 dash"], ["Peychaud's bitters", "1 dash"]], garnish: "Lemon twist",
    method: "Stir with ice and strain over a large cube.", collections: [] },

  // ---------- Champagne & Wine ----------
  { name: "Aperol Spritz", base: "champagne", type: "long", strength: "light", color: "orange", glass: "Wine glass",
    ings: [["Aperol", "60 ml"], ["Prosecco", "90 ml"], ["Soda water", "30 ml"]], garnish: "Orange slice",
    method: "Build over ice in a wine glass and stir gently.", collections: ["summer", "brunch", "party"] },
  { name: "Mimosa", base: "champagne", type: "long", strength: "light", color: "orange", glass: "Flute",
    ings: [["Champagne", "75 ml"], ["Orange juice", "75 ml"]], garnish: "Orange twist",
    method: "Pour juice into a flute and top with champagne.", collections: ["brunch", "engagement-party"] },
  { name: "Bellini", base: "champagne", type: "long", strength: "light", color: "pink", glass: "Flute",
    ings: [["Prosecco", "100 ml"], ["Peach purée", "50 ml"]], garnish: "",
    method: "Add purée to a flute and slowly top with prosecco.", collections: ["brunch", "engagement-party"] },
  { name: "Kir Royale", base: "champagne", type: "classic", strength: "light", color: "pink", glass: "Flute",
    ings: [["Champagne", "120 ml"], ["Crème de cassis", "15 ml"]], garnish: "Raspberry",
    method: "Add cassis to a flute and top with champagne.", collections: ["engagement-party"] },
  { name: "Champagne Cocktail", base: "champagne", type: "classic", strength: "light", color: "yellow", glass: "Flute",
    ings: [["Champagne", "120 ml"], ["Brandy", "10 ml"], ["Sugar", "1 cube"], ["Angostura bitters", "2 dashes"]], garnish: "Lemon twist",
    method: "Soak a sugar cube with bitters, add brandy and top with champagne.", collections: ["engagement-party"] },
  { name: "Hugo Spritz", base: "champagne", type: "long", strength: "light", color: "green", glass: "Wine glass",
    ings: [["Prosecco", "90 ml"], ["Elderflower liqueur", "20 ml"], ["Soda water", "30 ml"], ["Mint", "5 leaves"], ["Lime", "2 wedges"]], garnish: "Mint sprig",
    method: "Build over ice in a wine glass and stir gently.", collections: ["summer", "brunch"] },
  { name: "Sangria", base: "champagne", type: "long", strength: "light", color: "red", glass: "Wine glass",
    ings: [["Red wine", "150 ml"], ["Brandy", "20 ml"], ["Orange juice", "30 ml"], ["Simple syrup", "10 ml"], ["Orange", "slices"], ["Soda water", "30 ml"]], garnish: "Fruit slices",
    method: "Combine with fruit and chill for an hour; top with soda to serve.", collections: ["summer", "party"] },

  // ---------- Beer ----------
  { name: "Michelada", base: "beer", type: "long", strength: "light", color: "red", glass: "Pint",
    ings: [["Lager", "300 ml"], ["Lime juice", "20 ml"], ["Tomato juice", "60 ml"], ["Worcestershire sauce", "2 dashes"], ["Tabasco", "2 dashes"], ["Salt", "rim"]], garnish: "Salt rim",
    method: "Build in a salt-rimmed glass over ice, topping with beer.", collections: ["brunch", "summer"] },
  { name: "Shandy", base: "beer", type: "long", strength: "light", color: "yellow", glass: "Pint",
    ings: [["Lager", "250 ml"], ["Lemonade", "250 ml"]], garnish: "Lemon wedge",
    method: "Half fill with lager, top with lemonade.", collections: ["summer"] },
  { name: "Black Velvet", base: "beer", type: "long", strength: "light", color: "brown", glass: "Flute",
    ings: [["Stout", "75 ml"], ["Champagne", "75 ml"]], garnish: "",
    method: "Half fill with champagne and gently layer stout on top.", collections: [] },

  // ---------- Liqueur-based ----------
  { name: "Amaretto Sour", base: "liqueur", type: "sour", strength: "light", color: "yellow", glass: "Rocks",
    ings: [["Amaretto", "45 ml"], ["Lemon juice", "30 ml"], ["Simple syrup", "10 ml"], ["Egg white", "1"]], garnish: "Cherry",
    method: "Dry shake, then shake with ice and strain over fresh ice.", collections: [] },
  { name: "Grasshopper", base: "liqueur", type: "creamy", strength: "light", color: "green", glass: "Coupe",
    ings: [["Crème de menthe", "30 ml"], ["Crème de cacao", "30 ml"], ["Cream", "30 ml"]], garnish: "Mint leaf",
    method: "Shake hard with ice and strain into a chilled coupe.", collections: ["after-dinner"] },
  { name: "B-52", base: "liqueur", type: "shooter", strength: "medium", color: "brown", glass: "Shot",
    ings: [["Coffee liqueur", "10 ml"], ["Irish cream", "10 ml"], ["Triple sec", "10 ml"]], garnish: "",
    method: "Layer in order over the back of a spoon.", collections: ["party", "after-dinner"] },
  { name: "Mudslide", base: "liqueur", type: "frozen", strength: "medium", color: "brown", glass: "Hurricane",
    ings: [["Vodka", "30 ml"], ["Coffee liqueur", "30 ml"], ["Irish cream", "30 ml"], ["Vanilla ice cream", "2 scoops"]], garnish: "Chocolate drizzle",
    method: "Blend with a little ice until smooth.", collections: ["after-dinner"] },
  { name: "Campari Soda", base: "liqueur", type: "long", strength: "light", color: "red", glass: "Highball",
    ings: [["Campari", "50 ml"], ["Soda water", "100 ml"]], garnish: "Orange slice",
    method: "Build over ice and stir.", collections: ["summer"] },
  { name: "Americano", base: "liqueur", type: "long", strength: "light", color: "red", glass: "Highball",
    ings: [["Campari", "30 ml"], ["Sweet vermouth", "30 ml"], ["Soda water", "60 ml"]], garnish: "Orange slice",
    method: "Build over ice and top with soda.", collections: ["allseason-classics"] },
  { name: "Harvey Wallbanger", base: "liqueur", type: "long", strength: "light", color: "orange", glass: "Highball",
    ings: [["Vodka", "45 ml"], ["Orange juice", "90 ml"], ["Galliano", "15 ml"]], garnish: "Orange slice",
    method: "Build vodka and juice over ice, float the Galliano.", collections: [] },
  { name: "Midori Sour", base: "liqueur", type: "sour", strength: "light", color: "green", glass: "Rocks",
    ings: [["Melon liqueur", "45 ml"], ["Lemon juice", "20 ml"], ["Lime juice", "10 ml"], ["Soda water", "30 ml"]], garnish: "Cherry",
    method: "Shake melon liqueur and citrus, strain over ice and top with soda.", collections: ["party"] },

  // ---------- Non-alcoholic ----------
  { name: "Virgin Mojito", base: "non-alcoholic", type: "non-alcoholic", strength: "light", color: "green", glass: "Highball",
    ings: [["Lime juice", "25 ml"], ["Simple syrup", "20 ml"], ["Mint", "8 leaves"], ["Soda water", "150 ml"]], garnish: "Mint sprig",
    method: "Muddle mint with lime and syrup, add crushed ice and top with soda.", collections: ["summer", "brunch"] },
  { name: "Shirley Temple", base: "non-alcoholic", type: "non-alcoholic", strength: "light", color: "pink", glass: "Highball",
    ings: [["Ginger ale", "180 ml"], ["Grenadine", "15 ml"]], garnish: "Cherry",
    method: "Build over ice and stir.", collections: ["party"] },
  { name: "Virgin Mary", base: "non-alcoholic", type: "non-alcoholic", strength: "light", color: "red", glass: "Highball",
    ings: [["Tomato juice", "150 ml"], ["Lemon juice", "15 ml"], ["Worcestershire sauce", "3 dashes"], ["Tabasco", "2 dashes"], ["Celery salt", "1 pinch"]], garnish: "Celery stalk",
    method: "Roll between two tins with ice and strain into an ice-filled glass.", collections: ["brunch"] },
  { name: "Virgin Piña Colada", base: "non-alcoholic", type: "non-alcoholic", strength: "light", color: "white", glass: "Hurricane",
    ings: [["Pineapple juice", "120 ml"], ["Coconut cream", "45 ml"]], garnish: "Pineapple wedge",
    method: "Blend with crushed ice until smooth.", collections: ["summer"] },
  { name: "Cucumber Cooler", base: "non-alcoholic", type: "non-alcoholic", strength: "light", color: "green", glass: "Highball",
    ings: [["Cucumber", "4 slices"], ["Lime juice", "20 ml"], ["Simple syrup", "15 ml"], ["Mint", "5 leaves"], ["Tonic water", "120 ml"]], garnish: "Cucumber ribbon",
    method: "Muddle cucumber and mint with lime and syrup, add ice and top with tonic.", collections: ["summer"] },
  { name: "Arnold Palmer", base: "non-alcoholic", type: "non-alcoholic", strength: "light", color: "yellow", glass: "Highball",
    ings: [["Lemonade", "100 ml"], ["Iced tea", "100 ml"]], garnish: "Lemon wheel",
    method: "Mix equal parts chilled black tea and lemonade over ice.", collections: ["summer"] },
  { name: "Roy Rogers", base: "non-alcoholic", type: "non-alcoholic", strength: "light", color: "brown", glass: "Highball",
    ings: [["Cola", "180 ml"], ["Grenadine", "15 ml"]], garnish: "Cherry",
    method: "Build over ice and stir.", collections: [] },
  { name: "Strawberry Lemonade", base: "non-alcoholic", type: "non-alcoholic", strength: "light", color: "pink", glass: "Highball",
    ings: [["Strawberries", "4"], ["Lemon juice", "25 ml"], ["Simple syrup", "20 ml"], ["Soda water", "120 ml"]], garnish: "Strawberry",
    method: "Muddle strawberries with lemon and syrup, add ice and top with soda.", collections: ["summer", "brunch"] }
];
